ProgramSettings:
  jiraUrl: "https://issues.apache.org/jira"
  threadCount: 1
  issueInOneRequest: 50
  minTimeSleep: 1000
  maxTimeSleep: 60000
  port: 8080


DBSettings:
  dbUser: "postgres"
  dbPassword: "pgpwd"
  dbHost: "localhost"
  dbPort: 5432
  dbName: "jira_analyzer"
