rogramSettings:
  resourceTimeout: 5
  analyticsTimeout: 15
  bindAddress: "0.0.0.0"
  port: 8000

DBSettings:
  dbUser: "postgres"
  dbPassword: "pgpwd"
  dbHost: "localhost"
  dbPort: 5432
  dbName: "jira_analyzer"