name: GolangCI Lint Connector

on:
  pull_request:
    paths:
      - 'Connector/**'
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run GolangCI Lint for Connector

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install golangci-lint locally
        run: |
          mkdir -p "$HOME/.golangci/bin"
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$HOME/.golangci/bin" v1.54.2
          echo "$HOME/.golangci/bin" >> $GITHUB_PATH
          golangci-lint version

      - name: Run golangci-lint in Connector
        working-directory: Connector
        run: golangci-lint run --config .golangci.yml --timeout=5m
